spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.191:3306/ink3?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      minimum-idle: 10
  data:
    redis:
      host: 192.168.1.191
      port: 6379
      database: 1
      password: ${REDIS_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST}
  cloud:
    bus:
      enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 600s
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL}
minio:
  host: ${MINIO_HOST}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  review-bucket: ink3-prod-reviews-images
  book-bucket: ink3-prod-books-images
elasticsearch:
  url: http://s4.java21.net:9200
  index: ink3_books_prod
  key: ${ELASTIC_KEY}
logging:
  level:
    root: INFO
